apiVersion: apps/v1
kind: deployment 
metadata:
  name: radis
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLables:
      labels: 
        project: roboshop
        domain: radis
        tier: db    
  template:
    metadata:
      labels:
        project: roboshop
        domain: radis
        tier: db
    spec:
      containers:
      - name: radis
        image: radis
        imagePullPolicy: Always
---
apiVersion: v1 
kind: Service
metadata:
  name: radis-service
  namespace: roboshop
spec:
  selector:
    project: roboshop
    domain: radis
    tier: db          
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379