apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_HOST: cart
  CART_PORT: 8080
  USER_HOST: user
  USER_PORT: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: roboshop
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      domain: payment
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        domain: payment
        tier: app
    spec:
      containers:
      - name: payment
        image: narayanaguni/payment:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: payment
        - SecretRef:
            name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: roboshop
spec: 
  selector: 
    project: roboshop
    domain: payment
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080