apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      domain: mongodb
      tier: db
  template:
    metadata:
      labels: 
        project: roboshop
        domain: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: narayanaguni/mongodb:v1
      imagePullSecrets:
      - name: my-docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: roboshop
spec:
  selector:
      project: roboshop
      domain: mongodb
      tier: db   
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017  
  