apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namesapce: roboshop
data:
 MYSQL_DATABASE: "cities"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      domain: mysql
      tier: db
  template:
    metadata:
      lables: 
        project: roboshop
        domain: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: narayanaguni/mysql:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql
        - secretRef:
            name: mysql
---
  apiVersion: v1
  kind: Service
  metadata:
    name: mysql-service
    namespace: roboshop
  spec:
    selector:
      project: roboshop
      domain: mysql
      tier: db
    ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306