apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-configmap
  namespace: roboshop
data:
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      domain: catalogue
      tier: app
  template:
    metadata: 
      labels:
        project: roboshop
        domain: catalogue
        tier: app
    spec:
      containers:
      - name: catalogue
        image: narayanaguni/catalogue:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: catalogue-configmap

---
apiVersion: v1 
kind: Service
metadata:
  name: catalogue-service
  namespace: roboshop
spec:
  selector:
    project: roboshop
    domain: catalogue
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
