apiVersion: apps/v1
kind: Deployment 
metadata:
  name: redis
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
        project: roboshop
        domain: redis
        tier: db    
  template:
    metadata:
      labels:
        project: roboshop
        domain: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always
---
apiVersion: v1 
kind: Service
metadata:
  name: redis-service
  namespace: roboshop
spec:
  selector:
    project: roboshop
    domain: redis
    tier: db          
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379